### PR TITLE
User mutations

### PR DESCRIPTION
**Pull request by maxmwang**
Note: this branch depends on `user-auth` (#6). This branch has no conflicts with `user-auth`. 

# Summary 

Updated mongoose model and created mutations for the `User` module.

1. Added/removed properties from `User` schema
    [–] `password`
    [–] `is_superuser`
    [–] `date_joined` (replaced with createdAt, automatically created with timestamps)
    [+] `google_id`
    [+] `refresh_token`
3. Added [SchemaType options](https://mongoosejs.com/docs/schematypes.html#schematype-options)
4. Added mutations (all require user authentication):
    * `UpdateUserInfo(username, first_name, last_name)`
    * `UpdateUserMajor(major)`
    * `UpdateUserEmailPreferences(...)`
    * `DeleteUser`

### CODE REVIEW

**Review by zacharyzollman — COMMENTED** [review]
Nice! The expanded use of SchemaType options seems like a good idea.

It looks like [the current user schema](https://github.com/asuc-octo/berkeleytime/blob/b8fdf384d4ac37e89f2ce6235946c733e8db755f/backend/user/schema.py#L91) has one main user mutation. The way you broke up the fields among different mutations makes sense, but might require some additional work to integrate with frontend, so we might consider adding a more generic mutation.

I also wonder what the practical implications would be of finding one, modifying, and then saving rather than using calls like `findOneAndUpdate()`.

If a user could query any user, wouldn't that mean they could use someone's email address to query for their name, major, etc? Why not restrict to querying for their own data?

**Comment by maxmwang** [comment]
> It looks like [the current user schema](https://github.com/asuc-octo/berkeleytime/blob/b8fdf384d4ac37e89f2ce6235946c733e8db755f/backend/user/schema.py#L91) has one main user mutation. The way you broke up the fields among different mutations makes sense, but might require some additional work to integrate with frontend, so we might consider adding a more generic mutation.

Hm, that's true, but I wonder if it's worth to keep the queries broken up like so just to increase readability? Kev said something along the lines that multiple queries can be placed into a single POST request, so there is no additional cost to break up the queries other than a bit more refactoring in the frontend. 

Wouldn't be too hard to make it into one query, but I think splitting them up is something to consider. 

> I also wonder what the practical implications would be of finding one, modifying, and then saving rather than using calls like `findOneAndUpdate()`.

Good point. `findOneAndUpdate()` is more readable and probably better optimized, will fix. 

> If a user could query any user, wouldn't that mean they could use someone's email address to query for their name, major, etc? Why not restrict to querying for their own data?

True. Kev said he wanted this possible, not sure why (perhaps for friends?). Definitely seems like we should limit the fields given when querying for someone else's info, like removing the email address.

**Comment by zacharyzollman** [comment]
> Wouldn't be too hard to make it into one query, but I think splitting them up is something to consider.

That makes sense, let's try moving forward with the current queries.

> findOneAndUpdate() is more readable and probably better optimized, will fix.

Thanks for updating that!

> True. Kev said he wanted this possible, not sure why (perhaps for friends?).

I asked him and he said that was for testing prior to user auth being functional, so we shouldn't need it long-term.

**Comment by maxmwang** [comment]
Merged with `user-auth` in #6.

**Pull request closed without merging**
